apiVersion: apps/v1
kind: Deployment
metadata:
  name: parishioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parishioner
  template:
    metadata:
      labels:
        app: parishioner
    spec:
      containers:
      - name: parishioner
        image: servantcode/parishioner
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "200Mi"
        env:
        - name: ES_JAVA_OPTS 
          value: "-Xmx128m -Xms128m"
---
kind: Service
apiVersion: v1
metadata:
  name: parishioner
spec:
  selector:
    app: parishioner
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
