apiVersion: apps/v1
kind: Deployment
metadata:
  name: parishioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parishioner
  template:
    metadata:
      labels:
        app: parishioner
    spec:
      containers:
      - name: parishioner
        image: servantcode/parishioner
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 10
          periodSeconds: 30
        resources:
          limits:
            memory: "200Mi"
        env:
        - name: ES_JAVA_OPTS 
          value: "-Xmx128m -Xms128m"
        volumeMounts:
        - name: app-config
          mountPath: /usr/share/nginx/html/config
      volumes:
      - name: app-config
        configMap:
          name: app-config
---
kind: Service
apiVersion: v1
metadata:
  name: parishioner
spec:
  selector:
    app: parishioner
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
